// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package interconnect

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ObserverClient is the client API for Observer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObserverClient interface {
	ProcessGame(ctx context.Context, opts ...grpc.CallOption) (Observer_ProcessGameClient, error)
}

type observerClient struct {
	cc grpc.ClientConnInterface
}

func NewObserverClient(cc grpc.ClientConnInterface) ObserverClient {
	return &observerClient{cc}
}

func (c *observerClient) ProcessGame(ctx context.Context, opts ...grpc.CallOption) (Observer_ProcessGameClient, error) {
	stream, err := c.cc.NewStream(ctx, &Observer_ServiceDesc.Streams[0], "/field.Observer/ProcessGame", opts...)
	if err != nil {
		return nil, err
	}
	x := &observerProcessGameClient{stream}
	return x, nil
}

type Observer_ProcessGameClient interface {
	Send(*WordGuess) error
	Recv() (*WordStatus, error)
	grpc.ClientStream
}

type observerProcessGameClient struct {
	grpc.ClientStream
}

func (x *observerProcessGameClient) Send(m *WordGuess) error {
	return x.ClientStream.SendMsg(m)
}

func (x *observerProcessGameClient) Recv() (*WordStatus, error) {
	m := new(WordStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ObserverServer is the server API for Observer service.
// All implementations must embed UnimplementedObserverServer
// for forward compatibility
type ObserverServer interface {
	ProcessGame(Observer_ProcessGameServer) error
	mustEmbedUnimplementedObserverServer()
}

// UnimplementedObserverServer must be embedded to have forward compatible implementations.
type UnimplementedObserverServer struct {
}

func (UnimplementedObserverServer) ProcessGame(Observer_ProcessGameServer) error {
	return status.Errorf(codes.Unimplemented, "method ProcessGame not implemented")
}
func (UnimplementedObserverServer) mustEmbedUnimplementedObserverServer() {}

// UnsafeObserverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObserverServer will
// result in compilation errors.
type UnsafeObserverServer interface {
	mustEmbedUnimplementedObserverServer()
}

func RegisterObserverServer(s grpc.ServiceRegistrar, srv ObserverServer) {
	s.RegisterService(&Observer_ServiceDesc, srv)
}

func _Observer_ProcessGame_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ObserverServer).ProcessGame(&observerProcessGameServer{stream})
}

type Observer_ProcessGameServer interface {
	Send(*WordStatus) error
	Recv() (*WordGuess, error)
	grpc.ServerStream
}

type observerProcessGameServer struct {
	grpc.ServerStream
}

func (x *observerProcessGameServer) Send(m *WordStatus) error {
	return x.ServerStream.SendMsg(m)
}

func (x *observerProcessGameServer) Recv() (*WordGuess, error) {
	m := new(WordGuess)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Observer_ServiceDesc is the grpc.ServiceDesc for Observer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Observer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "field.Observer",
	HandlerType: (*ObserverServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessGame",
			Handler:       _Observer_ProcessGame_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "field.proto",
}
