// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: field.proto

package interconnect

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WordStatus_GameStatus int32

const (
	WordStatus_RUNNING WordStatus_GameStatus = 0
	WordStatus_WIN     WordStatus_GameStatus = 1
	WordStatus_DEFEAT  WordStatus_GameStatus = 2
)

// Enum value maps for WordStatus_GameStatus.
var (
	WordStatus_GameStatus_name = map[int32]string{
		0: "RUNNING",
		1: "WIN",
		2: "DEFEAT",
	}
	WordStatus_GameStatus_value = map[string]int32{
		"RUNNING": 0,
		"WIN":     1,
		"DEFEAT":  2,
	}
)

func (x WordStatus_GameStatus) Enum() *WordStatus_GameStatus {
	p := new(WordStatus_GameStatus)
	*p = x
	return p
}

func (x WordStatus_GameStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WordStatus_GameStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_field_proto_enumTypes[0].Descriptor()
}

func (WordStatus_GameStatus) Type() protoreflect.EnumType {
	return &file_field_proto_enumTypes[0]
}

func (x WordStatus_GameStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WordStatus_GameStatus.Descriptor instead.
func (WordStatus_GameStatus) EnumDescriptor() ([]byte, []int) {
	return file_field_proto_rawDescGZIP(), []int{0, 0}
}

type WordStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameState  string                `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	GameStatus WordStatus_GameStatus `protobuf:"varint,2,opt,name=game_status,json=gameStatus,proto3,enum=field.WordStatus_GameStatus" json:"game_status,omitempty"`
	Fuel       uint32                `protobuf:"varint,3,opt,name=fuel,proto3" json:"fuel,omitempty"`
}

func (x *WordStatus) Reset() {
	*x = WordStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_field_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordStatus) ProtoMessage() {}

func (x *WordStatus) ProtoReflect() protoreflect.Message {
	mi := &file_field_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordStatus.ProtoReflect.Descriptor instead.
func (*WordStatus) Descriptor() ([]byte, []int) {
	return file_field_proto_rawDescGZIP(), []int{0}
}

func (x *WordStatus) GetGameState() string {
	if x != nil {
		return x.GameState
	}
	return ""
}

func (x *WordStatus) GetGameStatus() WordStatus_GameStatus {
	if x != nil {
		return x.GameStatus
	}
	return WordStatus_RUNNING
}

func (x *WordStatus) GetFuel() uint32 {
	if x != nil {
		return x.Fuel
	}
	return 0
}

type WordGuess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Character string `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
}

func (x *WordGuess) Reset() {
	*x = WordGuess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_field_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordGuess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordGuess) ProtoMessage() {}

func (x *WordGuess) ProtoReflect() protoreflect.Message {
	mi := &file_field_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordGuess.ProtoReflect.Descriptor instead.
func (*WordGuess) Descriptor() ([]byte, []int) {
	return file_field_proto_rawDescGZIP(), []int{1}
}

func (x *WordGuess) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

var File_field_proto protoreflect.FileDescriptor

var file_field_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x22, 0xae, 0x01, 0x0a, 0x0a, 0x57, 0x6f, 0x72, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e,
	0x57, 0x6f, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x75, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x66, 0x75, 0x65, 0x6c, 0x22, 0x2e, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x57, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x46,
	0x45, 0x41, 0x54, 0x10, 0x02, 0x22, 0x29, 0x0a, 0x09, 0x57, 0x6f, 0x72, 0x64, 0x47, 0x75, 0x65,
	0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72,
	0x32, 0x42, 0x0a, 0x08, 0x4f, 0x62, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x0b,
	0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x2e, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x47, 0x75, 0x65, 0x73, 0x73, 0x1a, 0x11, 0x2e,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x28, 0x01, 0x30, 0x01, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_field_proto_rawDescOnce sync.Once
	file_field_proto_rawDescData = file_field_proto_rawDesc
)

func file_field_proto_rawDescGZIP() []byte {
	file_field_proto_rawDescOnce.Do(func() {
		file_field_proto_rawDescData = protoimpl.X.CompressGZIP(file_field_proto_rawDescData)
	})
	return file_field_proto_rawDescData
}

var file_field_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_field_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_field_proto_goTypes = []interface{}{
	(WordStatus_GameStatus)(0), // 0: field.WordStatus.GameStatus
	(*WordStatus)(nil),         // 1: field.WordStatus
	(*WordGuess)(nil),          // 2: field.WordGuess
}
var file_field_proto_depIdxs = []int32{
	0, // 0: field.WordStatus.game_status:type_name -> field.WordStatus.GameStatus
	2, // 1: field.Observer.ProcessGame:input_type -> field.WordGuess
	1, // 2: field.Observer.ProcessGame:output_type -> field.WordStatus
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_field_proto_init() }
func file_field_proto_init() {
	if File_field_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_field_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_field_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordGuess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_field_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_field_proto_goTypes,
		DependencyIndexes: file_field_proto_depIdxs,
		EnumInfos:         file_field_proto_enumTypes,
		MessageInfos:      file_field_proto_msgTypes,
	}.Build()
	File_field_proto = out.File
	file_field_proto_rawDesc = nil
	file_field_proto_goTypes = nil
	file_field_proto_depIdxs = nil
}
